  IF
    AttackedBy([GOODCUTOFF],DEFAULT)
    Allegiance(Myself,NEUTRAL)
	Global("X3WFMLAttack","LOCALS",0)
  THEN
    RESPONSE #100
	  SetGlobal("X3WFMLAttack","LOCALS",1)
      Enemy()
	  CreateCreature("X3WFRM",[1060.119],SE)
	  CreateCreature("X3WFRM",[1469.616],NW)
	  CreateCreature("X3WRM",[1206.251],SW)
	  CreateCreature("X3WRM",[1379.377],SW)
	  CreateCreature("X3WRM",[1351.427],W)
	  CreateCreature("X3WRE",[1104.336],SE)
 END 
